version: '3.3'

services:
  ram-postgres:
    container_name: ram-postgres
    image: postgres:14-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./web-server/database/postgres:/var/lib/postgres/data/
  ram-backend:
    container_name: ram-backend
    build: 
      context: ./web-server/
      dockerfile: dockerfile.backend
    command: sh scripts/backend.sh
    stdin_open: true
    tty: true
    depends_on:
      - ram-postgres
    links:
      - ram-postgres
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./web-server/:/app/
  ram-frontend:
    container_name: ram-frontend
    build:
      context: ./web-client/
      dockerfile: dockerfile.frontend
    command: sh scripts/frontend.sh
    ports:
      - 3000:3000
    volumes:
      - ./web-client/:/app/